namespace: "ttt"
name: "test"
version: "1.0.0"
readme: "README.md"
authors:
    - "Riyaz Mohammed"
dependencies:
license:
    - "IBM"
tags:
    - test
    - plugin
repository: "https://github.com/crazypks/terraform.git"
