namespace: "demo"
name: "custom-plugin"
version: "1.0.0"
readme: "README.md"
authors:
    - "Prasant Kumar"
dependencies:
license:
    - "TTN"
tags:
    - test
    - plugin
repository: "https://github.com/crazypks/terraform.git"
